"""All Nucula enclosure parameters in one place.

Measured board values are LOADED from analysis/*.json (generated by
scripts/extract_kicad_geometry.py from the KiCad board file). Only
*design decisions* live here as literals.

Provenance classes (mirrors docs/geometry_provenance.md):
  extracted_kicad             parsed from nucula-v2.kicad_pcb / footprint libs
  derived_kicad               computed from extracted geometry
  manufacturer_doc            from a Nucula repo document or component drawing
  conservative_assumption     documented guess; must be measured (see
                              MEASUREMENTS_NEEDED.md)
  enclosure_design_decision   our choice; a changeable parameter

Coordinate system (board-local, millimetres):
  Origin = main-board outline corner at KiCad (50, 50).
  u = KiCad X - 50  (0..60 across the board width)
  v = KiCad Y - 50  (0..73 main section; 75..110 keyboard section)
  z = 0 at the enclosure floor top surface; the PCB bottom face sits at
      z = PCB_SUPPORT_H.  KiCad axes are preserved (v grows toward the
      keyboard / cut end).
"""

from __future__ import annotations

import json
import os

_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ANALYSIS_DIR = os.path.join(_DIR, "analysis")


def _load(name):
    with open(os.path.join(ANALYSIS_DIR, name)) as f:
        return json.load(f)


class Measured:
    """Regenerated by scripts/extract_kicad_geometry.py - do not edit."""

    pcb = _load("pcb_geometry.json")
    comps = _load("component_geometry.json")

    board_t = pcb["board_thickness_mm"]              # 1.6  extracted_kicad
    board_w = pcb["board_size_mm"]["w"]              # 60.0 extracted_kicad
    board_l_full = pcb["board_size_mm"]["l"]         # 110.0 extracted_kicad
    outline = pcb["outer_outline_local_uv"]
    inner_cutouts = pcb["inner_cutouts_local_uv"]
    main_outline = pcb["main_outline_local_uv"]

    MAIN_V_END = 73.0                                # derived_kicad (routed gap edge)
    GAP_V0, GAP_V1 = 73.0, 75.0                      # derived_kicad
    # Mouse-bite support tabs across the gap (u ranges), derived_kicad
    TAB1_U = (8.75, 15.25)
    TAB2_U = (44.75, 51.25)
    # Central electrical bridge strip across the gap, derived_kicad
    BRIDGE_U = (27.25, 32.75)
    # ESP32-C3 antenna notch in the right edge, derived_kicad
    ESP_NOTCH = (55.0, 60.0, 47.14, 65.14)           # u0,u1,v0,v1

    # Key component placements (bbox_local_uv = pads+courtyard, derived_kicad)
    J1 = comps["J1"]["bbox_local_uv"]                # USB-C pads+cy
    J2 = comps["J2"]["bbox_local_uv"]                # JST PH pads+cy
    DS1 = comps["DS1"]["bbox_local_uv"]              # FH12 pads+cy
    U3 = comps["U3"]["bbox_local_uv"]                # ESP32 pads+cy
    U8 = comps["U8"]["bbox_local_uv"]
    J3 = comps["J3"]["bbox_local_uv"]
    J4 = comps["J4"]["bbox_local_uv"]
    J5 = comps["J5"]["bbox_local_uv"]
    U6 = comps["U6"]["bbox_local_uv"]
    SW1_C = (56.5, 34.0)                             # button plunger centres (pads)
    SW2_C = (56.5, 29.0)
    D3_C = (15.5, 44.0)                              # charge LED centre

    # NFC coil: manufacturer_doc "40x40 mm outer copper" (A1 footprint
    # Geometry property) centred at the A1 placement; cross-checked against
    # the extracted PCB antenna rule areas (u 8.25..53.25, v -1.5..43.5).
    NFC_RULE = (8.25, 53.25, -1.5, 43.5)             # extracted_kicad rule areas
    COIL_C = (30.75, 21.0)                           # A1 at, extracted_kicad
    COIL_SIZE = 40.0                                 # manufacturer_doc

    # ESP32 module STEP (repo 3D model): 18.0 wide, 20.0 long, 3.2 tall;
    # placed so the antenna section overhangs the edge notch.
    ESP_STEP = os.path.join(_DIR, "reference", "ESP32-C3-WROOM-02-N4.step")


# ---------------------------------------------------------------------------
# Measured component heights above board TOP face
# ---------------------------------------------------------------------------

COMP_HEIGHTS = {
    # ref: (height_mm, provenance)
    "J1": (3.31, "manufacturer_doc: GCT USB4105 drawing"),
    "J2": (5.60, "manufacturer_doc: JST PH SM4-TB drawing (housing 5.6)"),
    "DS1": (2.00, "manufacturer_doc: Hirose FH12A drawing"),
    "U3": (3.20, "extracted_kicad: repo STEP model bbox"),
    "U8": (2.70, "conservative_assumption: SOIC-16W JEDEC max"),
    "U6": (0.60, "conservative_assumption: HVQFN40 body"),
    "SW1": (1.80, "conservative_assumption: Omron B3U-1000P"),
    "SW2": (1.80, "conservative_assumption: Omron B3U-1000P"),
    "U1": (1.45, "conservative_assumption: SOT-23-5 JEDEC body max"),
    "D3": (0.70, "conservative_assumption: 0603 LED"),
    "Y1": (0.60, "conservative_assumption: 2016 crystal"),
    "L4": (2.20, "conservative_assumption: Coilcraft LPS4018"),
    "L1": (2.20, "conservative_assumption: Taiyo-Yuden NR-30xx"),
}
_PASSIVE_H = 1.00  # conservative_assumption: any 0603/0805/1206/SOD/SOT body


def comp_height(ref: str) -> float:
    if ref in COMP_HEIGHTS:
        return COMP_HEIGHTS[ref][0]
    return _PASSIVE_H


def comp_height_prov(ref: str) -> str:
    if ref in COMP_HEIGHTS:
        return COMP_HEIGHTS[ref][1]
    return "conservative_assumption: generic SMD passives <= 1.0"


# ---------------------------------------------------------------------------
# Design decisions (literals live ONLY here)
# ---------------------------------------------------------------------------

# --- shell process ----------------------------------------------------------
WALL_T = 1.60          # enclosure_design_decision (0.4mm nozzle x 4)
FLOOR_T = 1.40         # enclosure_design_decision
ROOF_T = 1.40          # enclosure_design_decision
CORNER_R = 3.0         # enclosure_design_decision: exterior vertical corners
FILLET_R = 0.0         # placeholder (profile chamfers handled per-feature)

PCB_XY_CLEARANCE = 0.35   # enclosure_design_decision: board edge to walls
PCB_Z_CLEARANCE = 0.40    # enclosure_design_decision: board bottom to pocket rims
COMP_Z_CLEARANCE = 0.70   # enclosure_design_decision: tallest body to lid floor
LID_LIP_ENGAGE = 1.60     # enclosure_design_decision: lid lip drop into bottom
LID_SHEAR_PLAY = 0.15     # enclosure_design_decision: lip-to-wall fit
END_REMNANT_ALLOW = 2.60  # enclosure_design_decision: mouse-bite remnant band
STOP_RIB_GAP = 0.30       # enclosure_design_decision: gap at routed cut edge

RAIL_LIP_T = 1.10         # enclosure_design_decision: lip thickness over board
RAIL_LIP_HOVER = 0.00     # lips touch board top by design (INTENDED contact)
RAIL_LIP_OVERHANG = 0.65  # enclosure_design_decision: lip overlaps board top
                         # (clears C41 courtyard 0.77 by 0.12)
PCB_SUPPORT_H = 1.60      # enclosure_design_decision: board bottom above floor

# --- fasteners (rev1: self-tapping into printed corner posts) ---------------
SCREW_D = 2.2             # enclosure_design_decision: M2 self-tapping
SCREW_PILOT_D = 1.70      # manufacturer-derived: PETG M2 pilot (coupon gauges)
POST_D = 4.60             # enclosure_design_decision
POST_CORNER_INSET = 2.90  # enclosure_design_decision: post centre from walls

# --- NFC ---------------------------------------------------------------------
NFC_WALL_T = 1.60         # enclosure_design_decision (allowed 1.2..2.0)
NFC_KEEPOUT_MARGIN = 0.0  # uses the PCB's own antenna rule areas verbatim

# --- battery (placeholder until a cell is chosen) ----------------------------
BATTERY_L = 30.0          # conservative_assumption: u-direction length
BATTERY_W = 22.0          # conservative_assumption: v-direction width
BATTERY_T = 6.0           # conservative_assumption: thickness (brief example)
BATTERY_CLEARANCE_XY = 1.0   # enclosure_design_decision: pocket slack
BATTERY_CLEARANCE_Z = 0.5    # enclosure_design_decision: swell + wire headroom
BATTERY_POCKET_FLOOR = 1.00  # enclosure_design_decision: wall below pocket
BATTERY_WIRE_D = 1.30     # manufacturer_doc: JST PH wire insulation <= 1.5
BATTERY_WIRE_COUNT = 2
WIRE_BEND_R = 2.60        # enclosure_design_decision: min bend radius
WIRE_OFFSET = 0.65        # enclosure_design_decision: wire-to-wire spacing/2
WIRE_SLACK = 0.13         # enclosure_design_decision: sweep radius margin
REMNANT_GAP = 0.50        # enclosure_design_decision: extra end-wall clearance
# Battery wire route (enclosure_design_decision).  J2 rear exit (u 10.0,
# v 50.9, z=BOARD_TOP+2.0 per JST drawing) -> -v corridor between the J2
# housing (v>=46.82, u<=10.0) and U1 (v>=49.8) -> +u/+v lane columns at
# u 19.2/20.6 (east of Q1, west of the stop ribs; between mouse-bite
# remnant zones) -> crosses the routed cut edge at v 73.58..75.02 ->
# vertical drop inside the remnant channel -> under-board run (z 0.75)
# -> battery terminals at the pocket's -u face.
WIRE_ROUTE_A = [   # wire 1 (+0.65 v offset through the exit corridor)
    (9.9, 51.55, 5.20),
    (11.5, 50.90, 6.40),
    (13.5, 50.20, 7.00),
    (17.5, 49.60, 7.00),
    (19.2, 52.00, 7.00),
    (19.2, 73.30, 7.00),
    (19.2, 74.30, 7.00),
    (19.2, 74.30, 0.78),
    (19.2, 62.00, 0.78),
    (19.2, 56.00, 0.78),
    (20.2, 51.00, 0.78),
]
WIRE_ROUTE_B = [   # wire 2
    (9.9, 50.25, 5.20),
    (11.5, 49.60, 6.40),
    (13.5, 48.90, 7.00),
    (17.5, 48.30, 7.00),
    (20.6, 51.50, 7.00),
    (20.6, 73.30, 7.00),
    (20.6, 74.30, 7.00),
    (20.6, 74.30, 0.78),
    (20.6, 62.00, 0.78),
    (20.6, 56.00, 0.78),
    (20.9, 51.00, 0.78),
]
WIRE_SWEEP_R = BATTERY_WIRE_D / 2.0 + WIRE_SLACK   # 0.78 per wire
# Full-board mode (keyboard attached): there is no cut edge, so the wires
# run the whole board at z 7.0 and drop through the 2.0 mm channel at the
# FACTORY board edge (v=110), then return under the keyboard section.
WIRE_ROUTE_A_FULL = [
    (9.9, 51.55, 5.20),
    (11.5, 50.90, 6.40),
    (13.5, 50.20, 7.00),
    (17.5, 49.60, 7.00),
    (19.2, 52.00, 7.00),
    (19.2, 108.50, 7.00),
    (19.2, 111.00, 7.00),
    (19.2, 111.00, 0.78),
    (19.2, 100.00, 0.78),
    (19.2, 60.00, 0.78),
    (20.2, 51.00, 0.78),
]
WIRE_ROUTE_B_FULL = [
    (9.9, 50.25, 5.20),
    (11.5, 49.60, 6.40),
    (13.5, 48.90, 7.00),
    (17.5, 48.30, 7.00),
    (20.6, 51.50, 7.00),
    (20.6, 108.50, 7.00),
    (20.6, 111.00, 7.00),
    (20.6, 111.00, 0.78),
    (20.6, 100.00, 0.78),
    (20.6, 60.00, 0.78),
    (20.9, 51.00, 0.78),
]
# Descent lane for battery wires (exit -> under-board pocket). Derived from
# the J2 rear-exit position (u 10.3, v 49.1..52.7, z ~ board_top+2.0) and the
# bare-laminate lane between D3 (v<=45.5) and U1 (v>=49.8).
WIRE_LANE = (10.8, 16.0, 45.9, 49.5)   # u0,u1,v0,v1 enclosure_design_decision

# --- USB-C -------------------------------------------------------------------
USB_PLUG_W = 13.00        # manufacturer_doc: GCT mating view plug envelope
USB_PLUG_H = 6.50         # manufacturer_doc: "6.5 Max." at mating view
USB_PLUG_REACH = 26.0     # enclosure_design_decision: cable bend service void
USB_OPENING_CLEAR = 0.60  # enclosure_design_decision: opening oversize
USB_BODY_V = (55.5, 68.4) # derived_kicad: J1 pads v-span + 0.5

# --- screen option (pop-out window) ------------------------------------------
# LANDSCAPE glass: long axis along u, so the display reads correctly with
# the device held keyboard-down (nucula-board device orientation: screen at
# the top, keypad underneath). The ribbon exits the +v short edge, centred
# on the DS1 socket (u = 30, pads along u; mounted panel pin 1 left /
# pin 24 right -- nucula-board docs/oled24). The real NFP1309-02Y panel's
# contact-edge side + exact outline still need physical confirmation
# (docs/MEASUREMENTS_NEEDED.md).
SCREEN_GLASS_W = 57.5     # conservative_assumption: 2.42" SSD1309 glass, long axis (u)
SCREEN_GLASS_L = 29.4     # conservative_assumption: short axis (v)
SCREEN_GLASS_T = 1.90     # conservative_assumption
SCREEN_ACTIVE_W = 55.0    # manufacturer_doc: SSD1309 2.42" active area
SCREEN_ACTIVE_L = 27.5    # manufacturer_doc
SCREEN_FLEX_EDGE_V = 53.0  # enclosure_design_decision: glass +v edge at the DS1
                           # courtyard edge (DS1 v 53.6..61.6); ribbon folds
                           # straight into the socket. Puts the screen band
                           # (v ~23.6..53.0) above the keyboard-side cluster.
SCREEN_CENTER_U = 30.0     # derived_kicad: DS1 pad-row centre (u)
SCREEN_DECK_BEZEL = 1.30   # enclosure_design_decision: bezel ring around the window
SCREEN_WINDOW_MARGIN = 1.2  # enclosure_design_decision: bezel around active
SCREEN_POP_T = 1.00       # enclosure_design_decision: pop-out panel thickness
SCREEN_BRIDGE_W = 0.60    # enclosure_design_decision: perforation bridge width
SCREEN_BRIDGE_N = 4       # enclosure_design_decision: bridges per side pair
SCREEN_RECESS_CLEAR = 0.35  # enclosure_design_decision: glass fit slack
SCREEN_DECK_RISE = None   # computed below

# --- buttons / LED ------------------------------------------------------------
BUTTON_HOLE_D = 3.20      # enclosure_design_decision
BUTTON_PLUNGER_D = 2.60   # enclosure_design_decision
BUTTON_PLUNGER_GAP = 0.30 # enclosure_design_decision
LED_HOLE_D = 2.20         # enclosure_design_decision
LED_WINDOW = True         # enclosure_design_decision

# --- keyboard-attached variant -------------------------------------------------
KB_J3_ACCESS = True       # enclosure_design_decision: V3 service blister
KB_J3_HATCH = True        # pop-out hatch over J3 in the blister roof
KB_HEADER_H = 8.70        # conservative_assumption: 1x09 2.54 vertical header
KB_BLISTER_WALL = 1.20    # enclosure_design_decision

# --- calibration coupon --------------------------------------------------------
COUPON_HOLE_LADDER = (1.55, 1.70, 1.85, 2.00, 2.20)  # pilot dia probes
COUPON_SLIT_LADDER = (0.30, 0.40, 0.50, 0.60)        # slit clearance probes
COUPON_THICK_STAIRS = (1.2, 1.4, 1.6, 1.8)           # board thickness gauges

# ---------------------------------------------------------------------------
# Variants
# ---------------------------------------------------------------------------
# Each variant is a dict consumed by cad/shell.py + scripts/build.py.
# board_mode: "main" (keyboard breakaway removed) | "full" (keyboard kept)

VARIANTS = {
    "coupon": {
        "label": "V0 calibration coupon",
        "board_mode": None,
        "parts": ("coupon",),
        "notes": "Print FIRST. Gauges pilot dia, board-thickness stairs, "
                 "lip bite, wire-lane slit, pop-out bridge feel.",
    },
    "minimal": {
        "label": "V1 minimal - no screen, no keyboard (board broken away)",
        "board_mode": "main",
        "parts": ("bottom", "lid"),
        "screen_window": False,
        "lid_variant": "closed",
        "notes": "Accessible USB-C + battery connector slot. Lid printed "
                 "closed (no window).",
    },
    "screen_popout": {
        "label": "V2 screen-ready - pop-out OLED window (board broken away)",
        "board_mode": "main",
        "parts": ("bottom", "lid"),
        "screen_window": True,
        "lid_variant": "popout",
        "notes": "Same bottom as V1. Lid prints with the screen window "
                 "closed; pop it out only if you fit the OLED glass.",
    },
    "full_keyboard": {
        "label": "V3 full-length - keyboard breakaway NOT removed",
        "board_mode": "full",
        "parts": ("bottom", "lid"),
        "screen_window": False,
        "lid_variant": "kb_blister",
        "notes": "Houses the 60x110 board with the keyboard section "
                 "attached. J3 keypad-header service blister with pop-out "
                 "hatch for a future keypad.",
    },
}


def derived() -> dict:
    """Quantities computed from the parameters above (single source)."""
    d = {}
    # interior cavity (board-local u,v ranges kept free for the board)
    d["int_u0"] = -WALL_T  # wall inner faces sit outside the board plane
    d["board_u0"], d["board_u1"] = 0.0, Measured.board_w
    # lid interior floor height above enclosure floor (z)
    tall_main = max(
        comp_height("J2"), comp_height("J1"), comp_height("U3"), comp_height("U8")
    )
    d["lid_int_z"] = PCB_SUPPORT_H + Measured.board_t + tall_main + COMP_Z_CLEARANCE
    # screen deck: glass must clear the USB shell (tallest thing it covers)
    d["deck_floor_z"] = PCB_SUPPORT_H + Measured.board_t + comp_height("J1") + 0.40
    d["deck_top_z"] = d["deck_floor_z"] + SCREEN_GLASS_T + SCREEN_RECESS_CLEAR + SCREEN_POP_T + 0.60
    # J2 wire apex clearance blister height (housing top + wire bend)
    d["j2_blister_z"] = PCB_SUPPORT_H + Measured.board_t + comp_height("J2") + BATTERY_WIRE_D + 0.70
    # keyboard blister interior height (header height if ever fitted)
    d["kb_blister_z"] = PCB_SUPPORT_H + Measured.board_t + KB_HEADER_H + 0.80
    # battery pocket
    d["pocket_z_top"] = PCB_SUPPORT_H - PCB_Z_CLEARANCE          # battery top limit
    d["pocket_z_bot"] = d["pocket_z_top"] - BATTERY_T - BATTERY_CLEARANCE_Z
    d["case_z_min"] = d["pocket_z_bot"] - BATTERY_POCKET_FLOOR   # battery bump face
    # battery pocket XY (u 7..55.6 keeps clear of corner zones; v 45.8..71.9)
    d["pocket_u"] = (7.0, 55.6)
    d["pocket_v"] = (45.8, 71.9)
    d["battery_u"] = (21.6, 21.6 + BATTERY_L)
    d["battery_v"] = (47.5, 47.5 + BATTERY_W)
    # USB wall opening (board-local v range, z range in enclosure coords)
    bz0 = PCB_SUPPORT_H + Measured.board_t - 1.60   # plug boot low edge
    bz1 = PCB_SUPPORT_H + Measured.board_t + comp_height("J1") / 2 + USB_PLUG_H / 2
    usb_c = (USB_BODY_V[0] + USB_BODY_V[1]) / 2.0
    half = USB_PLUG_W / 2.0 + USB_OPENING_CLEAR
    d["usb_open_v"] = (usb_c - half, usb_c + half)
    d["usb_open_z"] = (bz0 - USB_OPENING_CLEAR, bz1 + USB_OPENING_CLEAR)
    d["usb_mating_u"] = -0.80    # derived_kicad: J1 shell face overhangs edge
    d["end_wall_inner_v"] = Measured.MAIN_V_END + END_REMNANT_ALLOW + REMNANT_GAP
    # battery service slot in the left wall (aligns with J2 housing)
    d["bat_slot_v"] = (46.3, 54.2)
    d["bat_slot_z"] = (PCB_SUPPORT_H + 0.2, PCB_SUPPORT_H + Measured.board_t + comp_height("J2") + 0.4)
    return d


D = derived()
